### ISSUE TITLE
Example from the selenium-python documentation fails with wires

### ISSUE THREAD

**Issue by marco-c** [jgraham/wires#26]
```Python
from selenium import webdriver
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium.webdriver.common.keys import Keys

firefox_capabilities = DesiredCapabilities.FIREFOX
firefox_capabilities['marionette'] = True
firefox_capabilities['binary'] = 'tools/firefox/firefox-bin'

driver = webdriver.Firefox(capabilities=firefox_capabilities)

driver.get("http://www.python.org")
assert "Python" in driver.title
elem = driver.find_element_by_name("q")
elem.send_keys("pycon")
elem.send_keys(Keys.RETURN)
assert "No results found." not in driver.page_source
driver.close()
```

This test fails with:
```
Traceback (most recent call last):
  File "asd.py", line 16, in <module>
    assert "No results found." not in driver.page_source
  File "/usr/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 464, in page_source
    return self.execute(Command.GET_PAGE_SOURCE)['value']
  File "/usr/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 201, in execute
    self.error_handler.check_response(response)
  File "/usr/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 151, in check_response
    raise exception_class(value)
selenium.common.exceptions.WebDriverException: Message: {"error":"unknown command","message":"GET /session/b4ff4988-2ce7-4cce-85e9-59ab27787d2a/source did not match a known command"}
```

**Comment by vladikoff** [comment]
Is `page_source` still supported? I cannot find it in the WebDriver spec

**Comment by jgraham** [comment]
It's not a wire command, but selenium can still support it using execute_script.

**Comment by AutomatedTester** [comment]
Page source has been added in 83cf7a9dd9be0ce5bc2e563aea07d69c5264d038
