### ISSUE TITLE
NoSuchFrameException: Message: frame id has unexpected type

### ISSUE THREAD

**Issue by vladikoff** [jgraham/wires#46]
### Prepare a marionette setting
```
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

firefox_capabilities = DesiredCapabilities.FIREFOX
firefox_capabilities['marionette'] = True
firefox_capabilities['binary'] = '/Users/vladikoff/mozilla/mercurial/fx-team/objdir-frontend/dist/Nightly.app/Contents/MacOS/firefox'

```

### Test script
```
    def setUp(self):
        self.driver = webdriver.Firefox(capabilities=firefox_capabilities)
        self.driver.implicitly_wait(20)  # seconds

    def test_fxa_test(self):
        email = "fxatester" + str(random.random()) + "@restmail.net"

        self.driver.get("about:preferences#sync")
        elem = self.driver.find_element_by_css_selector("#noFxaSignUp")
        elem.click()

        self.driver.switch_to.frame("remote")
```

### Expected

Should be able to switch to the iframe on the about:accounts page. 

This works in stable Firefox without setting `firefox_capabilities['marionette'] = True`

### Actual

```

Error
Traceback (most recent call last):
  File "/Users/vladikoff/PycharmProjects/fxa-sync-e2e/tests/test_signup.py", line 40, in test_fxa_test
    self.driver.switch_to.frame("remote")
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/switch_to.py", line 67, in frame
    self._driver.execute(Command.SWITCH_TO_FRAME, {'id': frame_reference})
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/webdriver.py", line 201, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/remote/errorhandler.py", line 188, in check_response
    raise exception_class(message, screen, stacktrace)
NoSuchFrameException: Message: frame id has unexpected type
```

**Comment by vladikoff** [comment]
I have a simple repo here to make it easier to test this: https://github.com/vladikoff/fxa-sync-e2e/blob/master/tests/test_signup.py#L13

Tests passing with old webdriver: https://circleci.com/gh/vladikoff/fxa-sync-e2e/5

**Comment by AutomatedTester** [comment]
This is a change that has happened to WebDriver. Only an index or a WebElement is acceptable. See http://w3c.github.io/webdriver/webdriver-spec.html#switch-to-frame

**Comment by vladikoff** [comment]
Hey @AutomatedTester I updated the script to use an element here: https://github.com/vladikoff/fxa-sync-e2e/blob/hang-frame/tests/test_signup.py#L32

But when I run that with:

```
FIREFOX_BIN=/Applications/FirefoxNightly.app/Contents/MacOS/firefox-bin python tests/test_signup.py
```

It just hangs on that, any ideas?

**Comment by vladikoff** [comment]
ping @jgraham

**Comment by vladikoff** [comment]
cc @shane-tomlinson

**Comment by andreastt** [comment]
@vladikoff Can you supply a Gecko log with the `marionette.logging` preference set to "`TRACE`"?
