### ISSUE TITLE
Firefox Nightly crashes with latest changes to marionette webdriver

### ISSUE THREAD

**Issue by vladikoff** [jgraham/wires#49]
I'm on `changeset:   286985:a75d87f4cf52`. cc @AutomatedTester @jgraham 

With this sample file below (or JavaScript launcher):

```
import os
import unittest
import random
import time
import sys

from selenium.webdriver.firefox.firefox_binary import FirefoxBinary
from selenium import webdriver


from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

firefox_capabilities = DesiredCapabilities.FIREFOX
# Disable for now, https://github.com/jgraham/wires/issues/46
if "FIREFOX_BIN" in os.environ:
    print "Loading custom build..."
    firefox_capabilities['marionette'] = True
    firefox_capabilities['binary'] = os.environ["FIREFOX_BIN"]
    #firefox_capabilities['loggingPrefs'] = {'browser': 'ALL'}
    binary = FirefoxBinary(os.environ["FIREFOX_BIN"])

from selenium import webdriver

class FxaTests(unittest.TestCase):

    def setUp(self):
        self.driver = webdriver.Firefox(capabilities=firefox_capabilities, firefox_binary=binary)
        self.driver.implicitly_wait(20)  # seconds

    def test_fxa_signup(self):
        time.sleep(200000)
        time.sleep(200000)
        time.sleep(200000)
        time.sleep(200000)
        time.sleep(200000)
        time.sleep(200000)
        time.sleep(200000)
        time.sleep(200000)

    def tearDown(self):
        self.driver.close()

if __name__ == "__main__":
    unittest.main()

```

![image](https://cloud.githubusercontent.com/assets/128755/13561365/4150a6c0-e3fa-11e5-9997-67fdf35136e1.png)

**Comment by jgraham** [comment]
@andreastt did something change on the gecko side recently? I don't see a crash, but I can reproduce connecting, starting a session, setting the url, waiting, and then being unable to read the url.

**Comment by AutomatedTester** [comment]
@vladikoff 

The Python Selenium client pipes all logs to geckodriver.log. Can you add the log here so we can have a look at it?

**Comment by vladikoff** [comment]
Ok something strange was going on with those crash logs. I guess with the recent changes in Nightly the old webdriver code finally broke and won't work anymore and we **must use`marionette: True`**:

```
import unittest

from selenium.webdriver.firefox.firefox_binary import FirefoxBinary
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

firefox_capabilities = DesiredCapabilities.FIREFOX
binary = FirefoxBinary('/Users/vladikoff/mozilla/hgfirefox/firefox/objdir-frontend/dist/Nightly.app/Contents/MacOS/firefox')

from selenium import webdriver

class FxaTests(unittest.TestCase):

    def setUp(self):
        self.driver = webdriver.Firefox(capabilities=firefox_capabilities, firefox_binary=binary)
        self.driver.implicitly_wait(20)  # seconds

    def test_fxa_signup(self):
        driver = self.driver
        driver.get("http://www.python.org")
        self.assertIn("Python", driver.title)

    def tearDown(self):
        self.driver.close()

if __name__ == "__main__":
    unittest.main()
```

Otherwise it will crash with 

```
=====================================================================
ERROR: test_fxa_signup (__main__.FxaTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "sel.py", line 16, in setUp
    self.driver = webdriver.Firefox(capabilities=firefox_capabilities, firefox_binary=binary)
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/firefox/webdriver.py", line 78, in __init__
    self.binary, timeout)
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/firefox/extension_connection.py", line 51, in __init__
    self.binary.launch_browser(self.profile, timeout=timeout)
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/firefox/firefox_binary.py", line 68, in launch_browser
    self._wait_until_connectable(timeout=timeout)
  File "/usr/local/lib/python2.7/site-packages/selenium/webdriver/firefox/firefox_binary.py", line 98, in _wait_until_connectable
    raise WebDriverException("The browser appears to have exited "
WebDriverException: Message: The browser appears to have exited before we could connect. If you specified a log_file in the FirefoxBinary constructor, check it for details.
```
